#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
CGO_ENABLED=0 go build -ldflags "-X main.GITCOMMIT=$VERSION -linkmode external -extldflags -static" -o bin/go-machine-service
