#!/bin/bash

set -e

cd $(dirname $0)/..
. ./scripts/common_functions
set_project_vars

mkdir -p dist/artifacts

ARTIFACT_URL=$(curl -s https://api.github.com/repos/rancher/${PROJECT}/releases/latest | jq -r .assets[0].browser_download_url)
TAG=${TAG:-$(curl -s https://api.github.com/repos/rancher/${PROJECT}/releases/latest | jq -r .tag_name)}
TARGET="dist/artifacts/${PROJECT}.tar.xz"

echo "Downloading ${ARTIFACT_URL}"
curl -o ${TARGET} -L ${ARTIFACT_URL}

echo "Uncompressing..."
tar -xJvf ${TARGET} -C dist/artifacts/

IMAGE_NAME=${IMAGE:-"rancher/${PROJECT}"}:${TAG}

echo "Building Docker image"
docker build --rm -t ${IMAGE_NAME} -f Dockerfile.dist .
