#!/bin/bash

set -e

GITCOMMIT=`git rev-parse --short HEAD`

BASEDIR=$(dirname $0)

if [[ -z "$IN_DOCKER" ]]; then
    if [[ 0 -eq $(docker images | grep -ci $GITCOMMIT) ]]; then
        docker build --pull --force-rm -t $GITCOMMIT -f `pwd`/$BASEDIR/../generator/Dockerfile $BASEDIR/..
    fi
    docker run -v `pwd`/$BASEDIR/..:/go/src/github.com/rancherio/go-machine-service/ -e "IN_DOCKER=true" --entrypoint /go/src/github.com/rancherio/go-machine-service/scripts/generate $GITCOMMIT  
else
    cd /go/src/github.com/rancherio/go-machine-service/generator
    if [[ -e generated/* ]]; then
        rm -r generated/*
    fi
    go run generator.go
fi
